# permissions for end users to view servicewithdbs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: servicewithdb-viewer-role
rules:
- apiGroups:
  - test.test.org
  resources:
  - servicewithdbs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - test.test.org
  resources:
  - servicewithdbs/status
  verbs:
  - get
