# permissions for end users to edit servicewithdbs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: servicewithdb-editor-role
rules:
- apiGroups:
  - test.test.org
  resources:
  - servicewithdbs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - test.test.org
  resources:
  - servicewithdbs/status
  verbs:
  - get
